// Generated by scripts/generate-catalog.py. Do not edit.
#ifndef ROADCAST_CATALOG_GENERATED_H
#define ROADCAST_CATALOG_GENERATED_H

#define ROADCAST_SIGNAL_COUNT 815u

extern const uint64_t ROADCAST_CAN_SCHEMA_HASH;
extern const roadcast_signal_definition_t
    ROADCAST_SIGNALS[ROADCAST_SIGNAL_COUNT];

#endif
